import { useState, useEffect } from "react";

export default function Selector({
  onProvinceChange,
  onDistrictChange,
  errorProvince,
  errorDistrict,
  selectedProvince,
  selectedDistrict,
}) {
  const provinces = [
    { id: 1, province: "กรุงเทพมหานคร" },
    { id: 2, province: "สมุทรปราการ" },
    { id: 3, province: "นนทบุรี" },
    { id: 4, province: "ปทุมธานี" },
    { id: 5, province: "พระนครศรีอยุธยา" },
    { id: 6, province: "อ่างทอง" },
    { id: 7, province: "ลพบุรี" },
    { id: 8, province: "สิงห์บุรี" },
    { id: 9, province: "ชัยนาท" },
    { id: 10, province: "สระบุรี" },
    { id: 11, province: "ชลบุรี" },
    { id: 12, province: "ระยอง" },
    { id: 13, province: "จันทบุรี" },
    { id: 14, province: "ตราด" },
    { id: 15, province: "ฉะเชิงเทรา" },
    { id: 16, province: "ปราจีนบุรี" },
    { id: 17, province: "นครนายก" },
    { id: 18, province: "สระแก้ว" },
    { id: 19, province: "นครราชสีมา" },
    { id: 20, province: "บุรีรัมย์" },
    { id: 21, province: "สุรินทร์" },
    { id: 22, province: "ศรีสะเกษ" },
    { id: 23, province: "อุบลราชธานี" },
    { id: 24, province: "ยโสธร" },
    { id: 25, province: "ชัยภูมิ" },
    { id: 26, province: "อำนาจเจริญ" },
    { id: 27, province: "หนองบัวลำภู" },
    { id: 28, province: "ขอนแก่น" },
    { id: 29, province: "อุดรธานี" },
    { id: 30, province: "เลย" },
    { id: 31, province: "หนองคาย" },
    { id: 32, province: "มหาสารคาม" },
    { id: 33, province: "ร้อยเอ็ด" },
    { id: 34, province: "กาฬสินธุ์" },
    { id: 35, province: "สกลนคร" },
    { id: 36, province: "นครพนม" },
    { id: 37, province: "มุกดาหาร" },
    { id: 38, province: "เชียงใหม่" },
    { id: 39, province: "ลำพูน" },
    { id: 40, province: "ลำปาง" },
    { id: 41, province: "อุตรดิตถ์" },
    { id: 42, province: "แพร่" },
    { id: 43, province: "น่าน" },
    { id: 44, province: "พะเยา" },
    { id: 45, province: "เชียงราย" },
    { id: 46, province: "แม่ฮ่องสอน" },
    { id: 47, province: "นครสวรรค์" },
    { id: 48, province: "อุทัยธานี" },
    { id: 49, province: "กำแพงเพชร" },
    { id: 50, province: "ตาก" },
    { id: 51, province: "สุโขทัย" },
    { id: 52, province: "พิษณุโลก" },
    { id: 53, province: "พิจิตร" },
    { id: 54, province: "เพชรบูรณ์" },
    { id: 55, province: "ราชบุรี" },
    { id: 56, province: "กาญจนบุรี" },
    { id: 57, province: "สุพรรณบุรี" },
    { id: 58, province: "นครปฐม" },
    { id: 59, province: "สมุทรสาคร" },
    { id: 60, province: "สมุทรสงคราม" },
    { id: 61, province: "เพชรบุรี" },
    { id: 62, province: "ประจวบคีรีขันธ์" },
    { id: 63, province: "นครศรีธรรมราช" },
    { id: 64, province: "กระบี่" },
    { id: 65, province: "พังงา" },
    { id: 66, province: "ภูเก็ต" },
    { id: 67, province: "สุราษฎร์ธานี" },
    { id: 68, province: "ระนอง" },
    { id: 69, province: "ชุมพร" },
    { id: 70, province: "สงขลา" },
    { id: 71, province: "สตูล" },
    { id: 72, province: "ตรัง" },
    { id: 73, province: "พัทลุง" },
    { id: 74, province: "ปัตตานี" },
    { id: 75, province: "ยะลา" },
    { id: 76, province: "นราธิวาส" },
    { id: 77, province: "บึงกาฬ" },
  ];

  const districts = {
    1: [
      { id: 1, district: "พระนคร" },
      { id: 2, district: "ดุสิต" },
      { id: 3, district: "หนองจอก" },
      { id: 4, district: "บางรัก" },
      { id: 5, district: "บางเขน" },
      { id: 6, district: "บางกะปิ" },
      { id: 7, district: "ปทุมวัน" },
      { id: 8, district: "ป้อมปราบศัตรูพ่าย" },
      { id: 9, district: "พระโขนง" },
      { id: 10, district: "มีนบุรี" },
      { id: 11, district: "ลาดกระบัง" },
      { id: 12, district: "ยานนาวา" },
      { id: 13, district: "สัมพันธวงศ์" },
      { id: 14, district: "พญาไท" },
      { id: 15, district: "ธนบุรี" },
      { id: 16, district: "บางกอกใหญ่" },
      { id: 17, district: "ห้วยขวาง" },
      { id: 18, district: "คลองสาน" },
      { id: 19, district: "ตลิ่งชัน" },
      { id: 20, district: "บางกอกน้อย" },
      { id: 21, district: "บางขุนเทียน" },
      { id: 22, district: "ภาษีเจริญ" },
      { id: 23, district: "หนองแขม" },
      { id: 24, district: "ราษฎร์บูรณะ" },
      { id: 25, district: "บางพลัด" },
      { id: 26, district: "ดินแดง" },
      { id: 27, district: "บึงกุ่ม" },
      { id: 28, district: "สาทร" },
      { id: 29, district: "บางซื่อ" },
      { id: 30, district: "จตุจักร" },
      { id: 31, district: "บางคอแหลม" },
      { id: 32, district: "ประเวศ" },
      { id: 33, district: "คลองเตย" },
      { id: 34, district: "สวนหลวง" },
      { id: 35, district: "จอมทอง" },
      { id: 36, district: "ดอนเมือง" },
      { id: 37, district: "ราชเทวี" },
      { id: 38, district: "ลาดพร้าว" },
      { id: 39, district: "วัฒนา" },
      { id: 40, district: "บางแค" },
      { id: 41, district: "หลักสี่" },
      { id: 42, district: "สายไหม" },
      { id: 43, district: "คันนายาว" },
      { id: 44, district: "สะพานสูง" },
      { id: 45, district: "วังทองหลาง" },
      { id: 46, district: "คลองสามวา" },
      { id: 47, district: "บางนา" },
      { id: 48, district: "ทวีวัฒนา" },
      { id: 49, district: "ทุ่งครุ" },
      { id: 50, district: "บางบอน" },
    ],
    2: [
      { id: 52, district: "เมืองสมุทรปราการ" },
      { id: 53, district: "บางบ่อ" },
      { id: 54, district: "บางพลี" },
      { id: 55, district: "พระประแดง" },
      { id: 56, district: "พระสมุทรเจดีย์" },
      { id: 57, district: "บางเสาธง" },
    ],
    3: [
      { id: 58, district: "เมืองนนทบุรี" },
      { id: 59, district: "บางกรวย" },
      { id: 60, district: "บางใหญ่" },
      { id: 61, district: "บางบัวทอง" },
      { id: 62, district: "ไทรน้อย" },
      { id: 63, district: "ปากเกร็ด" },
    ],
    4: [
      { id: 66, district: "เมืองปทุมธานี" },
      { id: 67, district: "คลองหลวง" },
      { id: 68, district: "ธัญบุรี" },
      { id: 69, district: "หนองเสือ" },
      { id: 70, district: "ลาดหลุมแก้ว" },
      { id: 71, district: "ลำลูกกา" },
      { id: 72, district: "สามโคก" },
    ],
    5: [
      { id: 74, district: "พระนครศรีอยุธยา" },
      { id: 75, district: "ท่าเรือ" },
      { id: 76, district: "นครหลวง" },
      { id: 77, district: "บางไทร" },
      { id: 78, district: "บางบาล" },
      { id: 79, district: "บางปะอิน" },
      { id: 80, district: "บางปะหัน" },
      { id: 81, district: "ผักไห่" },
      { id: 82, district: "ภาชี" },
      { id: 83, district: "ลาดบัวหลวง" },
      { id: 84, district: "วังน้อย" },
      { id: 85, district: "เสนา" },
      { id: 86, district: "บางซ้าย" },
      { id: 87, district: "อุทัย" },
      { id: 88, district: "มหาราช" },
      { id: 89, district: "บ้านแพรก" },
    ],
    6: [
      { id: 90, district: "เมืองอ่างทอง" },
      { id: 91, district: "ไชโย" },
      { id: 92, district: "ป่าโมก" },
      { id: 93, district: "โพธิ์ทอง" },
      { id: 94, district: "แสวงหา" },
      { id: 95, district: "วิเศษชัยชาญ" },
      { id: 96, district: "สามโก้" },
    ],
    7: [
      { id: 97, district: "เมืองลพบุรี" },
      { id: 98, district: "พัฒนานิคม" },
      { id: 99, district: "โคกสำโรง" },
      { id: 100, district: "ชัยบาดาล" },
      { id: 101, district: "ท่าวุ้ง" },
      { id: 102, district: "บ้านหมี่" },
      { id: 103, district: "ท่าหลวง" },
      { id: 104, district: "สระโบสถ์" },
      { id: 105, district: "โคกเจริญ" },
      { id: 106, district: "ลำสนธิ" },
      { id: 107, district: "หนองม่วง" },
    ],
    8: [
      { id: 109, district: "เมืองสิงห์บุรี" },
      { id: 110, district: "บางระจัน" },
      { id: 111, district: "ค่ายบางระจัน" },
      { id: 112, district: "พรหมบุรี" },
      { id: 113, district: "ท่าช้าง" },
      { id: 114, district: "อินทร์บุรี" },
    ],
    9: [
      { id: 115, district: "เมืองชัยนาท" },
      { id: 116, district: "มโนรมย์" },
      { id: 117, district: "วัดสิงห์" },
      { id: 118, district: "สรรพยา" },
      { id: 119, district: "สรรคบุรี" },
      { id: 120, district: "หันคา" },
      { id: 121, district: "หนองมะโมง" },
      { id: 122, district: "เนินขาม" },
    ],
    10: [
      { id: 123, district: "เมืองสระบุรี" },
      { id: 124, district: "แก่งคอย" },
      { id: 125, district: "หนองแค" },
      { id: 126, district: "วิหารแดง" },
      { id: 127, district: "หนองแซง" },
      { id: 128, district: "บ้านหมอ" },
      { id: 129, district: "ดอนพุด" },
      { id: 130, district: "หนองโดน" },
      { id: 131, district: "พระพุทธบาท" },
      { id: 132, district: "เสาไห้" },
      { id: 133, district: "มวกเหล็ก" },
      { id: 134, district: "วังม่วง" },
      { id: 135, district: "เฉลิมพระเกียรติ" },
    ],
    11: [
      { id: 136, district: "เมืองชลบุรี" },
      { id: 137, district: "บ้านบึง" },
      { id: 138, district: "หนองใหญ่" },
      { id: 139, district: "บางละมุง" },
      { id: 140, district: "พานทอง" },
      { id: 141, district: "พนัสนิคม" },
      { id: 142, district: "ศรีราชา" },
      { id: 143, district: "เกาะสีชัง" },
      { id: 144, district: "สัตหีบ" },
      { id: 145, district: "บ่อทอง" },
      { id: 146, district: "เกาะจันทร์" },
    ],
    12: [
      { id: 151, district: "เมืองระยอง" },
      { id: 152, district: "บ้านฉาง" },
      { id: 153, district: "แกลง" },
      { id: 154, district: "วังจันทร์" },
      { id: 155, district: "บ้านค่าย" },
      { id: 156, district: "ปลวกแดง" },
      { id: 157, district: "เขาชะเมา" },
      { id: 158, district: "นิคมพัฒนา" },
    ],
    13: [
      { id: 160, district: "เมืองจันทบุรี" },
      { id: 161, district: "ขลุง" },
      { id: 162, district: "ท่าใหม่" },
      { id: 163, district: "โป่งน้ำร้อน" },
      { id: 164, district: "มะขาม" },
      { id: 165, district: "แหลมสิงห์" },
      { id: 166, district: "สอยดาว" },
      { id: 167, district: "แก่งหางแมว" },
      { id: 168, district: "นายายอาม" },
      { id: 169, district: "เขาคิชฌกูฏ" },
    ],
    14: [
      { id: 171, district: "เมืองตราด" },
      { id: 172, district: "คลองใหญ่" },
      { id: 173, district: "เขาสมิง" },
      { id: 174, district: "บ่อไร่" },
      { id: 175, district: "แหลมงอบ" },
      { id: 176, district: "เกาะกูด" },
      { id: 177, district: "เกาะช้าง" },
    ],
    15: [
      { id: 178, district: "เมืองฉะเชิงเทรา" },
      { id: 179, district: "บางคล้า" },
      { id: 180, district: "บางน้ำเปรี้ยว" },
      { id: 181, district: "บางปะกง" },
      { id: 182, district: "บ้านโพธิ์" },
      { id: 183, district: "พนมสารคาม" },
      { id: 184, district: "ราชสาส์น" },
      { id: 185, district: "สนามชัยเขต" },
      { id: 186, district: "แปลงยาว" },
      { id: 187, district: "ท่าตะเกียบ" },
      { id: 188, district: "คลองเขื่อน" },
    ],
    16: [
      { id: 189, district: "เมืองปราจีนบุรี" },
      { id: 190, district: "กบินทร์บุรี" },
      { id: 191, district: "นาดี" },
      { id: 192, district: "บ้านสร้าง" },
      { id: 193, district: "ประจันตคาม" },
      { id: 194, district: "ศรีมหาโพธิ" },
      { id: 195, district: "ศรีมโหสถ" },
    ],
    17: [
      { id: 202, district: "เมืองนครนายก" },
      { id: 203, district: "ปากพลี" },
      { id: 204, district: "บ้านนา" },
      { id: 205, district: "องครักษ์" },
    ],
    18: [
      { id: 206, district: "เมืองสระแก้ว" },
      { id: 207, district: "คลองหาด" },
      { id: 208, district: "ตาพระยา" },
      { id: 209, district: "วังน้ำเย็น" },
      { id: 210, district: "วัฒนานคร" },
      { id: 211, district: "อรัญประเทศ" },
      { id: 212, district: "เขาฉกรรจ์" },
      { id: 213, district: "โคกสูง" },
      { id: 214, district: "วังสมบูรณ์" },
    ],
    19: [
      { id: 215, district: "เมืองนครราชสีมา" },
      { id: 216, district: "ครบุรี" },
      { id: 217, district: "เสิงสาง" },
      { id: 218, district: "คง" },
      { id: 219, district: "บ้านเหลื่อม" },
      { id: 220, district: "จักราช" },
      { id: 221, district: "โชคชัย" },
      { id: 222, district: "ด่านขุนทด" },
      { id: 223, district: "โนนไทย" },
      { id: 224, district: "โนนสูง" },
      { id: 225, district: "ขามสะแกแสง" },
      { id: 226, district: "บัวใหญ่" },
      { id: 227, district: "ประทาย" },
      { id: 228, district: "ปักธงชัย" },
      { id: 229, district: "พิมาย" },
      { id: 230, district: "ห้วยแถลง" },
      { id: 231, district: "ชุมพวง" },
      { id: 232, district: "สูงเนิน" },
      { id: 233, district: "ขามทะเลสอ" },
      { id: 234, district: "สีคิ้ว" },
      { id: 235, district: "ปากช่อง" },
      { id: 236, district: "หนองบุญมาก" },
      { id: 237, district: "แก้งสนามนาง" },
      { id: 238, district: "โนนแดง" },
      { id: 239, district: "วังน้ำเขียว" },
      { id: 240, district: "เทพารักษ์" },
      { id: 241, district: "เมืองยาง" },
      { id: 242, district: "พระทองคำ" },
      { id: 243, district: "ลำทะเมนชัย" },
      { id: 244, district: "บัวลาย" },
      { id: 245, district: "สีดา" },
      { id: 246, district: "เฉลิมพระเกียรติ" },
    ],
    20: [
      { id: 250, district: "เมืองบุรีรัมย์" },
      { id: 251, district: "คูเมือง" },
      { id: 252, district: "กระสัง" },
      { id: 253, district: "นางรอง" },
      { id: 254, district: "หนองกี่" },
      { id: 255, district: "ละหานทราย" },
      { id: 256, district: "ประโคนชัย" },
      { id: 257, district: "บ้านกรวด" },
      { id: 258, district: "พุทไธสง" },
      { id: 259, district: "ลำปลายมาศ" },
      { id: 260, district: "สตึก" },
      { id: 261, district: "ปะคำ" },
      { id: 262, district: "นาโพธิ์" },
      { id: 263, district: "หนองหงส์" },
      { id: 264, district: "พลับพลาชัย" },
      { id: 265, district: "ห้วยราช" },
      { id: 266, district: "โนนสุวรรณ" },
      { id: 267, district: "ชำนิ" },
      { id: 268, district: "บ้านใหม่ไชยพจน์" },
      { id: 269, district: "โนนดินแดง" },
      { id: 270, district: "บ้านด่าน" },
      { id: 271, district: "แคนดง" },
      { id: 272, district: "เฉลิมพระเกียรติ" },
    ],
    21: [
      { id: 273, district: "เมืองสุรินทร์" },
      { id: 274, district: "ชุมพลบุรี" },
      { id: 275, district: "ท่าตูม" },
      { id: 276, district: "จอมพระ" },
      { id: 277, district: "ปราสาท" },
      { id: 278, district: "กาบเชิง" },
      { id: 279, district: "รัตนบุรี" },
      { id: 280, district: "สนม" },
      { id: 281, district: "ศีขรภูมิ" },
      { id: 282, district: "สังขะ" },
      { id: 283, district: "ลำดวน" },
      { id: 284, district: "สำโรงทาบ" },
      { id: 285, district: "บัวเชด" },
      { id: 286, district: "พนมดงรัก" },
      { id: 287, district: "ศรีณรงค์" },
      { id: 288, district: "เขวาสินรินทร์" },
      { id: 289, district: "โนนนารายณ์" },
    ],
    22: [
      { id: 290, district: "เมืองศรีสะเกษ" },
      { id: 291, district: "ยางชุมน้อย" },
      { id: 292, district: "กันทรารมย์" },
      { id: 293, district: "กันทรลักษ์" },
      { id: 294, district: "ขุขันธ์" },
      { id: 295, district: "ไพรบึง" },
      { id: 296, district: "ปรางค์กู่" },
      { id: 297, district: "ขุนหาญ" },
      { id: 298, district: "ราษีไศล" },
      { id: 299, district: "อุทุมพรพิสัย" },
      { id: 300, district: "บึงบูรพ์" },
      { id: 301, district: "ห้วยทับทัน" },
      { id: 302, district: "โนนคูณ" },
      { id: 303, district: "ศรีรัตนะ" },
      { id: 304, district: "น้ำเกลี้ยง" },
      { id: 305, district: "วังหิน" },
      { id: 306, district: "ภูสิงห์" },
      { id: 307, district: "เมืองจันทร์" },
      { id: 308, district: "เบญจลักษ์" },
      { id: 309, district: "พยุห์" },
      { id: 310, district: "โพธิ์ศรีสุวรรณ" },
      { id: 311, district: "ศิลาลาด" },
    ],
    23: [
      { id: 312, district: "เมืองอุบลราชธานี" },
      { id: 313, district: "ศรีเมืองใหม่" },
      { id: 314, district: "โขงเจียม" },
      { id: 315, district: "เขื่องใน" },
      { id: 316, district: "เขมราฐ" },
      { id: 317, district: "เดชอุดม" },
      { id: 318, district: "นาจะหลวย" },
      { id: 319, district: "น้ำยืน" },
      { id: 320, district: "บุณฑริก" },
      { id: 321, district: "ตระการพืชผล" },
      { id: 322, district: "กุดข้าวปุ้น" },
      { id: 324, district: "ม่วงสามสิบ" },
      { id: 325, district: "วารินชำราบ" },
      { id: 330, district: "พิบูลมังสาหาร" },
      { id: 331, district: "ตาลสุม" },
      { id: 332, district: "โพธิ์ไทร" },
      { id: 333, district: "สำโรง" },
      { id: 335, district: "ดอนมดแดง" },
      { id: 336, district: "สิรินธร" },
      { id: 337, district: "ทุ่งศรีอุดม" },
      { id: 340, district: "นาเยีย" },
      { id: 341, district: "นาตาล" },
      { id: 342, district: "เหล่าเสือโก้ก" },
      { id: 343, district: "สว่างวีระวงศ์" },
      { id: 344, district: "น้ำขุ่น" },
    ],
    24: [
      { id: 346, district: "เมืองยโสธร" },
      { id: 347, district: "ทรายมูล" },
      { id: 348, district: "กุดชุม" },
      { id: 349, district: "คำเขื่อนแก้ว" },
      { id: 350, district: "ป่าติ้ว" },
      { id: 351, district: "มหาชนะชัย" },
      { id: 352, district: "ค้อวัง" },
      { id: 353, district: "เลิงนกทา" },
      { id: 354, district: "ไทยเจริญ" },
    ],
    25: [
      { id: 355, district: "เมืองชัยภูมิ" },
      { id: 356, district: "บ้านเขว้า" },
      { id: 357, district: "คอนสวรรค์" },
      { id: 358, district: "เกษตรสมบูรณ์" },
      { id: 359, district: "หนองบัวแดง" },
      { id: 360, district: "จัตุรัส" },
      { id: 361, district: "บำเหน็จณรงค์" },
      { id: 362, district: "หนองบัวระเหว" },
      { id: 363, district: "เทพสถิต" },
      { id: 364, district: "ภูเขียว" },
      { id: 365, district: "บ้านแท่น" },
      { id: 366, district: "แก้งคร้อ" },
      { id: 367, district: "คอนสาร" },
      { id: 368, district: "ภักดีชุมพล" },
      { id: 369, district: "เนินสง่า" },
      { id: 370, district: "ซับใหญ่" },
    ],
    26: [
      { id: 380, district: "เมืองอำนาจเจริญ" },
      { id: 381, district: "ชานุมาน" },
      { id: 382, district: "ปทุมราชวงศา" },
      { id: 383, district: "พนา" },
      { id: 384, district: "เสนางคนิคม" },
      { id: 385, district: "หัวตะพาน" },
      { id: 386, district: "ลืออำนาจ" },
    ],
    27: [
      { id: 387, district: "เมืองหนองบัวลำภู" },
      { id: 388, district: "นากลาง" },
      { id: 389, district: "โนนสัง" },
      { id: 390, district: "ศรีบุญเรือง" },
      { id: 391, district: "สุวรรณคูหา" },
      { id: 392, district: "นาวัง" },
    ],
    28: [
      { id: 393, district: "เมืองขอนแก่น" },
      { id: 394, district: "บ้านฝาง" },
      { id: 395, district: "พระยืน" },
      { id: 396, district: "หนองเรือ" },
      { id: 397, district: "ชุมแพ" },
      { id: 398, district: "สีชมพู" },
      { id: 399, district: "น้ำพอง" },
      { id: 400, district: "อุบลรัตน์" },
      { id: 401, district: "กระนวน" },
      { id: 402, district: "บ้านไผ่" },
      { id: 403, district: "เปือยน้อย" },
      { id: 404, district: "พล" },
      { id: 405, district: "แวงใหญ่" },
      { id: 406, district: "แวงน้อย" },
      { id: 407, district: "หนองสองห้อง" },
      { id: 408, district: "ภูเวียง" },
      { id: 409, district: "มัญจาคีรี" },
      { id: 410, district: "ชนบท" },
      { id: 411, district: "เขาสวนกวาง" },
      { id: 412, district: "ภูผาม่าน" },
      { id: 413, district: "ซำสูง" },
      { id: 414, district: "โคกโพธิ์ไชย" },
      { id: 415, district: "หนองนาคำ" },
      { id: 416, district: "บ้านแฮด" },
      { id: 417, district: "โนนศิลา" },
      { id: 418, district: "เวียงเก่า" },
    ],
    29: [
      { id: 421, district: "เมืองอุดรธานี" },
      { id: 422, district: "กุดจับ" },
      { id: 423, district: "หนองวัวซอ" },
      { id: 424, district: "กุมภวาปี" },
      { id: 425, district: "โนนสะอาด" },
      { id: 426, district: "หนองหาน" },
      { id: 427, district: "ทุ่งฝน" },
      { id: 428, district: "ไชยวาน" },
      { id: 429, district: "ศรีธาตุ" },
      { id: 430, district: "วังสามหมอ" },
      { id: 431, district: "บ้านดุง" },
      { id: 437, district: "บ้านผือ" },
      { id: 438, district: "น้ำโสม" },
      { id: 439, district: "เพ็ญ" },
      { id: 440, district: "สร้างคอม" },
      { id: 441, district: "หนองแสง" },
      { id: 442, district: "นายูง" },
      { id: 443, district: "พิบูลย์รักษ์" },
      { id: 444, district: "กู่แก้ว" },
      { id: 445, district: "ประจักษ์ศิลปาคม" },
    ],
    30: [
      { id: 446, district: "เมืองเลย" },
      { id: 447, district: "นาด้วง" },
      { id: 448, district: "เชียงคาน" },
      { id: 449, district: "ปากชม" },
      { id: 450, district: "ด่านซ้าย" },
      { id: 451, district: "นาแห้ว" },
      { id: 452, district: "ภูเรือ" },
      { id: 453, district: "ท่าลี่" },
      { id: 454, district: "วังสะพุง" },
      { id: 455, district: "ภูกระดึง" },
      { id: 456, district: "ภูหลวง" },
      { id: 457, district: "ผาขาว" },
      { id: 458, district: "เอราวัณ" },
      { id: 459, district: "หนองหิน" },
    ],
    31: [
      { id: 460, district: "เมืองหนองคาย" },
      { id: 461, district: "ท่าบ่อ" },
      { id: 464, district: "โพนพิสัย" },
      { id: 466, district: "ศรีเชียงใหม่" },
      { id: 467, district: "สังคม" },
      { id: 473, district: "สระใคร" },
      { id: 474, district: "เฝ้าไร่" },
      { id: 475, district: "รัตนวาปี" },
      { id: 476, district: "โพธิ์ตาก" },
    ],
    32: [
      { id: 477, district: "เมืองมหาสารคาม" },
      { id: 478, district: "แกดำ" },
      { id: 479, district: "โกสุมพิสัย" },
      { id: 480, district: "กันทรวิชัย" },
      { id: 481, district: "เชียงยืน" },
      { id: 482, district: "บรบือ" },
      { id: 483, district: "นาเชือก" },
      { id: 484, district: "พยัคฆภูมิพิสัย" },
      { id: 485, district: "วาปีปทุม" },
      { id: 486, district: "นาดูน" },
      { id: 487, district: "ยางสีสุราช" },
      { id: 488, district: "กุดรัง" },
      { id: 489, district: "ชื่นชม" },
    ],
    33: [
      { id: 491, district: "เมืองร้อยเอ็ด" },
      { id: 492, district: "เกษตรวิสัย" },
      { id: 493, district: "ปทุมรัตต์" },
      { id: 494, district: "จตุรพักตรพิมาน" },
      { id: 495, district: "ธวัชบุรี" },
      { id: 496, district: "พนมไพร" },
      { id: 497, district: "โพนทอง" },
      { id: 498, district: "โพธิ์ชัย" },
      { id: 499, district: "หนองพอก" },
      { id: 500, district: "เสลภูมิ" },
      { id: 501, district: "สุวรรณภูมิ" },
      { id: 502, district: "เมืองสรวง" },
      { id: 503, district: "โพนทราย" },
      { id: 504, district: "อาจสามารถ" },
      { id: 505, district: "เมยวดี" },
      { id: 506, district: "ศรีสมเด็จ" },
      { id: 507, district: "จังหาร" },
      { id: 508, district: "เชียงขวัญ" },
      { id: 509, district: "หนองฮี" },
      { id: 510, district: "ทุ่งเขาหลวง" },
    ],
    34: [
      { id: 511, district: "เมืองกาฬสินธุ์" },
      { id: 512, district: "นามน" },
      { id: 513, district: "กมลาไสย" },
      { id: 514, district: "ร่องคำ" },
      { id: 515, district: "กุฉินารายณ์" },
      { id: 516, district: "เขาวง" },
      { id: 517, district: "ยางตลาด" },
      { id: 518, district: "ห้วยเม็ก" },
      { id: 519, district: "สหัสขันธ์" },
      { id: 520, district: "คำม่วง" },
      { id: 521, district: "ท่าคันโท" },
      { id: 522, district: "หนองกุงศรี" },
      { id: 523, district: "สมเด็จ" },
      { id: 524, district: "ห้วยผึ้ง" },
      { id: 525, district: "สามชัย" },
      { id: 526, district: "นาคู" },
      { id: 527, district: "ดอนจาน" },
      { id: 528, district: "ฆ้องชัย" },
    ],
    35: [
      { id: 529, district: "เมืองสกลนคร" },
      { id: 530, district: "กุสุมาลย์" },
      { id: 531, district: "กุดบาก" },
      { id: 532, district: "พรรณานิคม" },
      { id: 533, district: "พังโคน" },
      { id: 534, district: "วาริชภูมิ" },
      { id: 535, district: "นิคมน้ำอูน" },
      { id: 536, district: "วานรนิวาส" },
      { id: 537, district: "คำตากล้า" },
      { id: 538, district: "บ้านม่วง" },
      { id: 539, district: "อากาศอำนวย" },
      { id: 540, district: "สว่างแดนดิน" },
      { id: 541, district: "ส่องดาว" },
      { id: 542, district: "เต่างอย" },
      { id: 543, district: "โคกศรีสุพรรณ" },
      { id: 544, district: "เจริญศิลป์" },
      { id: 545, district: "โพนนาแก้ว" },
      { id: 546, district: "ภูพาน" },
    ],
    36: [
      { id: 549, district: "เมืองนครพนม" },
      { id: 550, district: "ปลาปาก" },
      { id: 551, district: "ท่าอุเทน" },
      { id: 552, district: "บ้านแพง" },
      { id: 553, district: "ธาตุพนม" },
      { id: 554, district: "เรณูนคร" },
      { id: 555, district: "นาแก" },
      { id: 556, district: "ศรีสงคราม" },
      { id: 557, district: "นาหว้า" },
      { id: 558, district: "โพนสวรรค์" },
      { id: 559, district: "นาทม" },
      { id: 560, district: "วังยาง" },
    ],
    37: [
      { id: 561, district: "เมืองมุกดาหาร" },
      { id: 562, district: "นิคมคำสร้อย" },
      { id: 563, district: "ดอนตาล" },
      { id: 564, district: "ดงหลวง" },
      { id: 565, district: "คำชะอี" },
      { id: 566, district: "หว้านใหญ่" },
      { id: 567, district: "หนองสูง" },
    ],
    38: [
      { id: 568, district: "เมืองเชียงใหม่" },
      { id: 569, district: "จอมทอง" },
      { id: 570, district: "แม่แจ่ม" },
      { id: 571, district: "เชียงดาว" },
      { id: 572, district: "ดอยสะเก็ด" },
      { id: 573, district: "แม่แตง" },
      { id: 574, district: "แม่ริม" },
      { id: 575, district: "สะเมิง" },
      { id: 576, district: "ฝาง" },
      { id: 577, district: "แม่อาย" },
      { id: 578, district: "พร้าว" },
      { id: 579, district: "สันป่าตอง" },
      { id: 580, district: "สันกำแพง" },
      { id: 581, district: "สันทราย" },
      { id: 582, district: "หางดง" },
      { id: 583, district: "ฮอด" },
      { id: 584, district: "ดอยเต่า" },
      { id: 585, district: "อมก๋อย" },
      { id: 586, district: "สารภี" },
      { id: 587, district: "เวียงแหง" },
      { id: 588, district: "ไชยปราการ" },
      { id: 589, district: "แม่วาง" },
      { id: 590, district: "แม่ออน" },
      { id: 591, district: "ดอยหล่อ" },
    ],
    39: [
      { id: 595, district: "เมืองลำพูน" },
      { id: 596, district: "แม่ทา" },
      { id: 597, district: "บ้านโฮ่ง" },
      { id: 598, district: "ลี้" },
      { id: 599, district: "ทุ่งหัวช้าง" },
      { id: 600, district: "ป่าซาง" },
      { id: 601, district: "บ้านธิ" },
      { id: 602, district: "เวียงหนองล่อง" },
    ],
    40: [
      { id: 603, district: "เมืองลำปาง" },
      { id: 604, district: "แม่เมาะ" },
      { id: 605, district: "เกาะคา" },
      { id: 606, district: "เสริมงาม" },
      { id: 607, district: "งาว" },
      { id: 608, district: "แจ้ห่ม" },
      { id: 609, district: "วังเหนือ" },
      { id: 610, district: "เถิน" },
      { id: 611, district: "แม่พริก" },
      { id: 612, district: "แม่ทะ" },
      { id: 613, district: "สบปราบ" },
      { id: 614, district: "ห้างฉัตร" },
      { id: 615, district: "เมืองปาน" },
    ],
    41: [
      { id: 616, district: "เมืองอุตรดิตถ์" },
      { id: 617, district: "ตรอน" },
      { id: 618, district: "ท่าปลา" },
      { id: 619, district: "น้ำปาด" },
      { id: 620, district: "ฟากท่า" },
      { id: 621, district: "บ้านโคก" },
      { id: 622, district: "พิชัย" },
      { id: 623, district: "ลับแล" },
      { id: 624, district: "ทองแสนขัน" },
    ],
    42: [
      { id: 625, district: "เมืองแพร่" },
      { id: 626, district: "ร้องกวาง" },
      { id: 627, district: "ลอง" },
      { id: 628, district: "สูงเม่น" },
      { id: 629, district: "เด่นชัย" },
      { id: 630, district: "สอง" },
      { id: 631, district: "วังชิ้น" },
      { id: 632, district: "หนองม่วงไข่" },
    ],
    43: [
      { id: 633, district: "เมืองน่าน" },
      { id: 634, district: "แม่จริม" },
      { id: 635, district: "บ้านหลวง" },
      { id: 636, district: "นาน้อย" },
      { id: 637, district: "ปัว" },
      { id: 638, district: "ท่าวังผา" },
      { id: 639, district: "เวียงสา" },
      { id: 640, district: "ทุ่งช้าง" },
      { id: 641, district: "เชียงกลาง" },
      { id: 642, district: "นาหมื่น" },
      { id: 643, district: "สันติสุข" },
      { id: 644, district: "บ่อเกลือ" },
      { id: 645, district: "สองแคว" },
      { id: 646, district: "ภูเพียง" },
      { id: 647, district: "เฉลิมพระเกียรติ" },
    ],
    44: [
      { id: 648, district: "เมืองพะเยา" },
      { id: 649, district: "จุน" },
      { id: 650, district: "เชียงคำ" },
      { id: 651, district: "เชียงม่วน" },
      { id: 652, district: "ดอกคำใต้" },
      { id: 653, district: "ปง" },
      { id: 654, district: "แม่ใจ" },
      { id: 655, district: "ภูซาง" },
      { id: 656, district: "ภูกามยาว" },
    ],
    45: [
      { id: 657, district: "เมืองเชียงราย" },
      { id: 658, district: "เวียงชัย" },
      { id: 659, district: "เชียงของ" },
      { id: 660, district: "เทิง" },
      { id: 661, district: "พาน" },
      { id: 662, district: "ป่าแดด" },
      { id: 663, district: "แม่จัน" },
      { id: 664, district: "เชียงแสน" },
      { id: 665, district: "แม่สาย" },
      { id: 666, district: "แม่สรวย" },
      { id: 667, district: "เวียงป่าเป้า" },
      { id: 668, district: "พญาเม็งราย" },
      { id: 669, district: "เวียงแก่น" },
      { id: 670, district: "ขุนตาล" },
      { id: 671, district: "แม่ฟ้าหลวง" },
      { id: 672, district: "แม่ลาว" },
      { id: 673, district: "เวียงเชียงรุ้ง" },
      { id: 674, district: "ดอยหลวง" },
    ],
    46: [
      { id: 675, district: "เมืองแม่ฮ่องสอน" },
      { id: 676, district: "ขุนยวม" },
      { id: 677, district: "ปาย" },
      { id: 678, district: "แม่สะเรียง" },
      { id: 679, district: "แม่ลาน้อย" },
      { id: 680, district: "สบเมย" },
      { id: 681, district: "ปางมะผ้า" },
    ],
    47: [
      { id: 683, district: "เมืองนครสวรรค์" },
      { id: 684, district: "โกรกพระ" },
      { id: 685, district: "ชุมแสง" },
      { id: 686, district: "หนองบัว" },
      { id: 687, district: "บรรพตพิสัย" },
      { id: 688, district: "เก้าเลี้ยว" },
      { id: 689, district: "ตาคลี" },
      { id: 690, district: "ท่าตะโก" },
      { id: 691, district: "ไพศาลี" },
      { id: 692, district: "พยุหะคีรี" },
      { id: 693, district: "ลาดยาว" },
      { id: 694, district: "ตากฟ้า" },
      { id: 695, district: "แม่วงก์" },
      { id: 696, district: "แม่เปิน" },
      { id: 697, district: "ชุมตาบง" },
    ],
    48: [
      { id: 701, district: "เมืองอุทัยธานี" },
      { id: 702, district: "ทัพทัน" },
      { id: 703, district: "สว่างอารมณ์" },
      { id: 704, district: "หนองฉาง" },
      { id: 705, district: "หนองขาหย่าง" },
      { id: 706, district: "บ้านไร่" },
      { id: 707, district: "ลานสัก" },
      { id: 708, district: "ห้วยคต" },
    ],
    49: [
      { id: 709, district: "เมืองกำแพงเพชร" },
      { id: 710, district: "ไทรงาม" },
      { id: 711, district: "คลองลาน" },
      { id: 712, district: "ขาณุวรลักษบุรี" },
      { id: 713, district: "คลองขลุง" },
      { id: 714, district: "พรานกระต่าย" },
      { id: 715, district: "ลานกระบือ" },
      { id: 716, district: "ทรายทองวัฒนา" },
      { id: 717, district: "ปางศิลาทอง" },
      { id: 718, district: "บึงสามัคคี" },
      { id: 719, district: "โกสัมพีนคร" },
    ],
    50: [
      { id: 720, district: "เมืองตาก" },
      { id: 721, district: "บ้านตาก" },
      { id: 722, district: "สามเงา" },
      { id: 723, district: "แม่ระมาด" },
      { id: 724, district: "ท่าสองยาง" },
      { id: 725, district: "แม่สอด" },
      { id: 726, district: "พบพระ" },
      { id: 727, district: "อุ้มผาง" },
      { id: 728, district: "วังเจ้า" },
    ],
    51: [
      { id: 730, district: "เมืองสุโขทัย" },
      { id: 731, district: "บ้านด่านลานหอย" },
      { id: 732, district: "คีรีมาศ" },
      { id: 733, district: "กงไกรลาศ" },
      { id: 734, district: "ศรีสัชนาลัย" },
      { id: 735, district: "ศรีสำโรง" },
      { id: 736, district: "สวรรคโลก" },
      { id: 737, district: "ศรีนคร" },
      { id: 738, district: "ทุ่งเสลี่ยม" },
    ],
    52: [
      { id: 739, district: "เมืองพิษณุโลก" },
      { id: 740, district: "นครไทย" },
      { id: 741, district: "ชาติตระการ" },
      { id: 742, district: "บางระกำ" },
      { id: 743, district: "บางกระทุ่ม" },
      { id: 744, district: "พรหมพิราม" },
      { id: 745, district: "วัดโบสถ์" },
      { id: 746, district: "วังทอง" },
      { id: 747, district: "เนินมะปราง" },
    ],
    53: [
      { id: 748, district: "เมืองพิจิตร" },
      { id: 749, district: "วังทรายพูน" },
      { id: 750, district: "โพธิ์ประทับช้าง" },
      { id: 751, district: "ตะพานหิน" },
      { id: 752, district: "บางมูลนาก" },
      { id: 753, district: "โพทะเล" },
      { id: 754, district: "สามง่าม" },
      { id: 755, district: "ทับคล้อ" },
      { id: 756, district: "สากเหล็ก" },
      { id: 757, district: "บึงนาราง" },
      { id: 758, district: "ดงเจริญ" },
      { id: 759, district: "วชิรบารมี" },
    ],
    54: [
      { id: 760, district: "เมืองเพชรบูรณ์" },
      { id: 761, district: "ชนแดน" },
      { id: 762, district: "หล่มสัก" },
      { id: 763, district: "หล่มเก่า" },
      { id: 764, district: "วิเชียรบุรี" },
      { id: 765, district: "ศรีเทพ" },
      { id: 766, district: "หนองไผ่" },
      { id: 767, district: "บึงสามพัน" },
      { id: 768, district: "น้ำหนาว" },
      { id: 769, district: "วังโป่ง" },
      { id: 770, district: "เขาค้อ" },
    ],
    55: [
      { id: 771, district: "เมืองราชบุรี" },
      { id: 772, district: "จอมบึง" },
      { id: 773, district: "สวนผึ้ง" },
      { id: 774, district: "ดำเนินสะดวก" },
      { id: 775, district: "บ้านโป่ง" },
      { id: 776, district: "บางแพ" },
      { id: 777, district: "โพธาราม" },
      { id: 778, district: "ปากท่อ" },
      { id: 779, district: "วัดเพลง" },
      { id: 780, district: "บ้านคา" },
    ],
    56: [
      { id: 782, district: "เมืองกาญจนบุรี" },
      { id: 783, district: "ไทรโยค" },
      { id: 784, district: "บ่อพลอย" },
      { id: 785, district: "ศรีสวัสดิ์" },
      { id: 786, district: "ท่ามะกา" },
      { id: 787, district: "ท่าม่วง" },
      { id: 788, district: "ทองผาภูมิ" },
      { id: 789, district: "สังขละบุรี" },
      { id: 790, district: "พนมทวน" },
      { id: 791, district: "เลาขวัญ" },
      { id: 792, district: "ด่านมะขามเตี้ย" },
      { id: 793, district: "หนองปรือ" },
      { id: 794, district: "ห้วยกระเจา" },
    ],
    57: [
      { id: 797, district: "เมืองสุพรรณบุรี" },
      { id: 798, district: "เดิมบางนางบวช" },
      { id: 799, district: "ด่านช้าง" },
      { id: 800, district: "บางปลาม้า" },
      { id: 801, district: "ศรีประจันต์" },
      { id: 802, district: "ดอนเจดีย์" },
      { id: 803, district: "สองพี่น้อง" },
      { id: 804, district: "สามชุก" },
      { id: 805, district: "อู่ทอง" },
      { id: 806, district: "หนองหญ้าไซ" },
    ],
    58: [
      { id: 807, district: "เมืองนครปฐม" },
      { id: 808, district: "กำแพงแสน" },
      { id: 809, district: "นครชัยศรี" },
      { id: 810, district: "ดอนตูม" },
      { id: 811, district: "บางเลน" },
      { id: 812, district: "สามพราน" },
      { id: 813, district: "พุทธมณฑล" },
    ],
    59: [
      { id: 814, district: "เมืองสมุทรสาคร" },
      { id: 815, district: "กระทุ่มแบน" },
      { id: 816, district: "บ้านแพ้ว" },
    ],
    60: [
      { id: 817, district: "เมืองสมุทรสงคราม" },
      { id: 818, district: "บางคนที" },
      { id: 819, district: "อัมพวา" },
    ],
    61: [
      { id: 820, district: "เมืองเพชรบุรี" },
      { id: 821, district: "เขาย้อย" },
      { id: 822, district: "หนองหญ้าปล้อง" },
      { id: 823, district: "ชะอำ" },
      { id: 824, district: "ท่ายาง" },
      { id: 825, district: "บ้านลาด" },
      { id: 826, district: "บ้านแหลม" },
      { id: 827, district: "แก่งกระจาน" },
    ],
    62: [
      { id: 828, district: "เมืองประจวบคีรีขันธ์" },
      { id: 829, district: "กุยบุรี" },
      { id: 830, district: "ทับสะแก" },
      { id: 831, district: "บางสะพาน" },
      { id: 832, district: "บางสะพานน้อย" },
      { id: 833, district: "ปราณบุรี" },
      { id: 834, district: "หัวหิน" },
      { id: 835, district: "สามร้อยยอด" },
    ],
    63: [
      { id: 836, district: "เมืองนครศรีธรรมราช" },
      { id: 837, district: "พรหมคีรี" },
      { id: 838, district: "ลานสกา" },
      { id: 839, district: "ฉวาง" },
      { id: 840, district: "พิปูน" },
      { id: 841, district: "เชียรใหญ่" },
      { id: 842, district: "ชะอวด" },
      { id: 843, district: "ท่าศาลา" },
      { id: 844, district: "ทุ่งสง" },
      { id: 845, district: "นาบอน" },
      { id: 846, district: "ทุ่งใหญ่" },
      { id: 847, district: "ปากพนัง" },
      { id: 848, district: "ร่อนพิบูลย์" },
      { id: 849, district: "สิชล" },
      { id: 850, district: "ขนอม" },
      { id: 851, district: "หัวไทร" },
      { id: 852, district: "บางขัน" },
      { id: 853, district: "ถ้ำพรรณรา" },
      { id: 854, district: "จุฬาภรณ์" },
      { id: 855, district: "พระพรหม" },
      { id: 856, district: "นบพิตำ" },
      { id: 857, district: "ช้างกลาง" },
      { id: 858, district: "เฉลิมพระเกียรติ" },
    ],
    64: [
      { id: 864, district: "เมืองกระบี่" },
      { id: 865, district: "เขาพนม" },
      { id: 866, district: "เกาะลันตา" },
      { id: 867, district: "คลองท่อม" },
      { id: 868, district: "อ่าวลึก" },
      { id: 869, district: "ปลายพระยา" },
      { id: 870, district: "ลำทับ" },
      { id: 871, district: "เหนือคลอง" },
    ],
    65: [
      { id: 872, district: "เมืองพังงา" },
      { id: 873, district: "เกาะยาว" },
      { id: 874, district: "กะปง" },
      { id: 875, district: "ตะกั่วทุ่ง" },
      { id: 876, district: "ตะกั่วป่า" },
      { id: 877, district: "คุระบุรี" },
      { id: 878, district: "ทับปุด" },
      { id: 879, district: "ท้ายเหมือง" },
    ],
    66: [
      { id: 880, district: "เมืองภูเก็ต" },
      { id: 881, district: "กะทู้" },
      { id: 882, district: "ถลาง" },
    ],
    67: [
      { id: 884, district: "เมืองสุราษฎร์ธานี" },
      { id: 885, district: "กาญจนดิษฐ์" },
      { id: 886, district: "ดอนสัก" },
      { id: 887, district: "เกาะสมุย" },
      { id: 888, district: "เกาะพะงัน" },
      { id: 889, district: "ไชยา" },
      { id: 890, district: "ท่าชนะ" },
      { id: 891, district: "คีรีรัฐนิคม" },
      { id: 892, district: "บ้านตาขุน" },
      { id: 893, district: "พนม" },
      { id: 894, district: "ท่าฉาง" },
      { id: 895, district: "บ้านนาสาร" },
      { id: 896, district: "บ้านนาเดิม" },
      { id: 897, district: "เคียนซา" },
      { id: 898, district: "เวียงสระ" },
      { id: 899, district: "พระแสง" },
      { id: 900, district: "พุนพิน" },
      { id: 901, district: "ชัยบุรี" },
      { id: 902, district: "วิภาวดี" },
    ],
    68: [
      { id: 905, district: "เมืองระนอง" },
      { id: 906, district: "ละอุ่น" },
      { id: 907, district: "กะเปอร์" },
      { id: 908, district: "กระบุรี" },
      { id: 909, district: "สุขสำราญ" },
    ],
    69: [
      { id: 910, district: "เมืองชุมพร" },
      { id: 911, district: "ท่าแซะ" },
      { id: 912, district: "ปะทิว" },
      { id: 913, district: "หลังสวน" },
      { id: 914, district: "ละแม" },
      { id: 915, district: "พะโต๊ะ" },
      { id: 916, district: "สวี" },
      { id: 917, district: "ทุ่งตะโก" },
    ],
    70: [
      { id: 918, district: "เมืองสงขลา" },
      { id: 919, district: "สทิงพระ" },
      { id: 920, district: "จะนะ" },
      { id: 921, district: "นาทวี" },
      { id: 922, district: "เทพา" },
      { id: 923, district: "สะบ้าย้อย" },
      { id: 924, district: "ระโนด" },
      { id: 925, district: "กระแสสินธุ์" },
      { id: 926, district: "รัตภูมิ" },
      { id: 927, district: "สะเดา" },
      { id: 928, district: "หาดใหญ่" },
      { id: 929, district: "นาหม่อม" },
      { id: 930, district: "ควนเนียง" },
      { id: 931, district: "บางกล่ำ" },
      { id: 932, district: "สิงหนคร" },
      { id: 933, district: "คลองหอยโข่ง" },
    ],
    71: [
      { id: 936, district: "เมืองสตูล" },
      { id: 937, district: "ควนโดน" },
      { id: 938, district: "ควนกาหลง" },
      { id: 939, district: "ท่าแพ" },
      { id: 940, district: "ละงู" },
      { id: 941, district: "ทุ่งหว้า" },
      { id: 942, district: "มะนัง" },
    ],
    72: [
      { id: 943, district: "เมืองตรัง" },
      { id: 944, district: "กันตัง" },
      { id: 945, district: "ย่านตาขาว" },
      { id: 946, district: "ปะเหลียน" },
      { id: 947, district: "สิเกา" },
      { id: 948, district: "ห้วยยอด" },
      { id: 949, district: "วังวิเศษ" },
      { id: 950, district: "นาโยง" },
      { id: 951, district: "รัษฎา" },
      { id: 952, district: "หาดสำราญ" },
    ],
    73: [
      { id: 954, district: "เมืองพัทลุง" },
      { id: 955, district: "กงหรา" },
      { id: 956, district: "เขาชัยสน" },
      { id: 957, district: "ตะโหมด" },
      { id: 958, district: "ควนขนุน" },
      { id: 959, district: "ปากพะยูน" },
      { id: 960, district: "ศรีบรรพต" },
      { id: 961, district: "ป่าบอน" },
      { id: 962, district: "บางแก้ว" },
      { id: 963, district: "ป่าพะยอม" },
      { id: 964, district: "ศรีนครินทร์" },
    ],
    74: [
      { id: 965, district: "เมืองปัตตานี" },
      { id: 966, district: "โคกโพธิ์" },
      { id: 967, district: "หนองจิก" },
      { id: 968, district: "ปะนาเระ" },
      { id: 969, district: "มายอ" },
      { id: 970, district: "ทุ่งยางแดง" },
      { id: 971, district: "สายบุรี" },
      { id: 972, district: "ไม้แก่น" },
      { id: 973, district: "ยะหริ่ง" },
      { id: 974, district: "ยะรัง" },
      { id: 975, district: "กะพ้อ" },
      { id: 976, district: "แม่ลาน" },
    ],
    75: [
      { id: 977, district: "เมืองยะลา" },
      { id: 978, district: "เบตง" },
      { id: 979, district: "บันนังสตา" },
      { id: 980, district: "ธารโต" },
      { id: 981, district: "ยะหา" },
      { id: 982, district: "รามัน" },
      { id: 983, district: "กาบัง" },
      { id: 984, district: "กรงปินัง" },
    ],
    76: [
      { id: 985, district: "เมืองนราธิวาส" },
      { id: 986, district: "ตากใบ" },
      { id: 987, district: "บาเจาะ" },
      { id: 988, district: "ยี่งอ" },
      { id: 989, district: "ระแงะ" },
      { id: 990, district: "รือเสาะ" },
      { id: 991, district: "ศรีสาคร" },
      { id: 992, district: "แว้ง" },
      { id: 993, district: "สุคิริน" },
      { id: 994, district: "สุไหงโก-ลก" },
      { id: 995, district: "สุไหงปาดี" },
      { id: 996, district: "จะแนะ" },
      { id: 997, district: "เจาะไอร้อง" },
    ],
    77: [
      { id: 999, district: "เมืองบึงกาฬ" },
      { id: 1000, district: "เซกา" },
      { id: 1001, district: "โซ่พิสัย" },
      { id: 1002, district: "พรเจริญ" },
      { id: 1003, district: "ศรีวิไล" },
      { id: 1004, district: "บึงโขงหลง" },
      { id: 1005, district: "ปากคาด" },
      { id: 1006, district: "บุ่งคล้า" },
    ],
  };
  const [localSelectedProvince, setLocalSelectedProvince] =
    useState(selectedProvince);
  const [localSelectedDistrict, setLocalSelectedDistrict] =
    useState(selectedDistrict);

  useEffect(() => {
    setLocalSelectedProvince(selectedProvince);
    setLocalSelectedDistrict(selectedDistrict);
  }, [selectedProvince, selectedDistrict]);

  const handleProvinceChange = (event) => {
    const selectedOption = provinces.find(
      (province) => province.id === parseInt(event.target.value)
    );
    if (localSelectedProvince?.id !== selectedOption.id) {
      setLocalSelectedProvince(selectedOption);
      setLocalSelectedDistrict(null); // รีเซ็ตค่าอำเภอเป็นค่าว่างเมื่อเปลี่ยนจังหวัด
    }
    onProvinceChange(selectedOption); // เรียกฟังก์ชัน callback เมื่อค่าจังหวัดเปลี่ยนแปลง
  };

  const handleDistrictChange = (event) => {
    const selectedOption = districts[localSelectedProvince.id].find(
      (district) => district.id === parseInt(event.target.value)
    );
    setLocalSelectedDistrict(selectedOption);
    onDistrictChange(selectedOption); // เรียกฟังก์ชัน callback เมื่อค่าอำเภอเปลี่ยนแปลง
  };

  // สมมติว่า provinces เป็น array ที่มาจาก data source ของคุณ
  const sortedProvinces = provinces.sort((a, b) =>
    a.province.localeCompare(b.province)
  );

  return (
    <div className="flex gap-4">
      <div className="w-[205px]">
        <label
          htmlFor="province-select"
          className=" mb-2 text-sm font-bold text-gray-700"
        >
          Province
        </label>
        <select
          id="province-select"
          value={localSelectedProvince ? localSelectedProvince.id : ""}
          onChange={handleProvinceChange}
          className="w-full focus:outline-none focus:ring-2 border border-gray-300  rounded-md px-2 py-2"
        >
          <option value="" disabled>
            เลือกจังหวัด
          </option>
          {sortedProvinces.map((province) => (
            <option key={province.id} value={province.id}>
              {province.province}
            </option>
          ))}
        </select>

        {errorProvince && (
          <div className="bg-red-200">
            <small className="absolute text-red-500 ">{errorProvince}</small>
          </div>
        )}
      </div>
      <div className="w-[205px]">
        <label
          htmlFor="district-select"
          className=" mb-2 text-sm font-bold text-gray-700"
        >
          District
        </label>
        <select
          id="district-select"
          value={localSelectedDistrict ? localSelectedDistrict.id : ""}
          onChange={handleDistrictChange}
          className="w-full focus:outline-none focus:ring-2 border border-gray-300  rounded-md px-2 py-2"
          disabled={!localSelectedProvince}
        >
          <option value="" disabled>
            เลือกอำเภอ
          </option>
          {localSelectedProvince &&
            districts[localSelectedProvince.id]
              .sort((a, b) => a.district.localeCompare(b.district))
              .map((district) => (
                <option key={district.id} value={district.id}>
                  {district.district}
                </option>
              ))}
        </select>
        {errorDistrict && (
          <div className="bg-red-200">
            <small className="absolute text-red-500 ">{errorDistrict}</small>
          </div>
        )}
      </div>
    </div>
  );
}
